from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://www.amazon.in/")
# driver.maximize_window()
# driver.minimize_window()
#print(driver.title)
#print(driver.current_url)
#driver.fullscreen_window()
#driver.refresh()
#driver.close()
#driver.quit()
#driver.set_page_load_timeout(30)
driver.implicitly_wait(5)
#ele = driver.find_element(By.ID,"twotabsearchtextbox")
#ele = driver.find_element(By.NAME,"")
#ele = driver.find_element(By.CSS_SELECTOR,"")
#ele = driver.find_element(By.CLASS_NAME,"")
#ele = driver.find_element(By.LINK_TEXT,"")
#ele = driver.find_element(By.TAG_NAME,"")
ele = driver.find_element(By.XPATH,"//*[@id='twotabsearchtextbox']")
ele.send_keys("Apple")
ele.clear()